name: supabasetime
description: Track your mood

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.6
  get_it: ^7.6.0
  http: ^0.13.6
  image_picker: ^0.8.7+5
  provider: ^6.0.5
  supabase_flutter: ^1.9.1
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
